### ISSUE TITLE
deps-manifests doesn't work on hydro

### ISSUE THREAD

**Issue by asiron** [ros/rospack#41]
I have a problem on Hydro running on Ubuntu 12.04
I tried installing ar_pose on seperate rosbuild workspace, but I had issues.
It seems like rospack deps-manifests is not working.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 562, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 544, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 271, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 246, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 236, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 337, in _init_posix
    makefile = _get_makefile_filename()
  File "/usr/lib/python2.7/sysconfig.py", line 331, in _get_makefile_filename
    return os.path.join(get_path('platstdlib').replace("/usr/local","/usr",1), "config" + (sys.pydebug and "_d" or ""), "Makefile")
AttributeError: 'module' object has no attribute 'pydebug'
```

Problem is the when I open python I can access pydebug from sys module.
I changed this file /usr/lib/python2.7/sysconfig.py to print sys.executable and it's running correct python from /usr/bin/python, from which I can access pydebug.

I did a small work around and hardcoded 'False' instead of sys.pydebug, but after I receive other error

```
     import subprocess
   File "/usr/lib/python2.7/subprocess.py", line 429, in <module>
      import select
  ImportError: No module named select
  Error in sys.excepthook:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
      from io import StringIO
    File "/usr/lib/python2.7/io.py", line 60, in <module>
      import _io
  ImportError: /usr/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS4_EncodeUTF32

  Original exception was:
  Traceback (most recent call last):
    File "/usr/lib/pymodules/python2.7/rosdep2/__init__.py", line 40, in <module>
      from .installers import InstallerContext, Installer, \
    File "/usr/lib/pymodules/python2.7/rosdep2/installers.py", line 32, in <module>
      import subprocess
    File "/usr/lib/python2.7/subprocess.py", line 429, in <module>
      import select
  ImportError: No module named select
  [rospack] Error: could not find python module 'rosdep2.rospack'. is rosdep up-to-date (at least 0.10.4)?
```

but my version of rosdep is 0.10.27, so I have no idea what is wrong with this.

Thank in advance

**Comment by tfoote** [comment]
This looks a lot like this problem: http://answers.ros.org/question/148981/import-select-importerror-no-module-named-select/

Where the user had setup a bunch of custom PYTHONPATH elements.

**Comment by asiron** [comment]
Yes, I have seen this issue, but my PYTHONPATH has only hydro packages and Nao QI dir

```
/opt/ros/hydro/lib/python2.7/dist-packages:/home/asiron/NAO/Software/SDK/NAOqi SDK/C++/naoqi-sdk-1.12.5-linux32/lib
```

**Comment by tfoote** [comment]
Can you test it without the NAOqi on your path? ​

**Comment by asiron** [comment]
I've just tested it, still the same issue

**Comment by tfoote** [comment]
There must be something about your environment. rospack is working fine on all our tests systems. And the only line of code which is failing are imports of system libraries. 

I would suggest that you find the root of the first problem instead of modifying the system packages. If you've done that elsewhere it might be causing this problem.

**Comment by dirk-thomas** [comment]
I will close this issue since it does not contain enough information to investigate the described problem and no other system seems to have the problem. Please feel free to comment with more information and we a are happy to help you debug the problem.
